package org.redhat.bajaservicios;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(6a80f5b5cb64e0489baa7903a6bb0901)
 */
@org.kie.api.definition.type.Label(value = "Agrupacion")
public class Agrupacion  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "IdAgrupacion")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer idAgrupacion;
    
    @org.kie.api.definition.type.Label(value = "Nombre agrupacion")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String nombreAgrupacion;

    public Agrupacion() {
    }

    public Agrupacion(java.lang.Integer idAgrupacion, java.lang.String nombreAgrupacion) {
        this.idAgrupacion = idAgrupacion;
        this.nombreAgrupacion = nombreAgrupacion;
    }


    
    public java.lang.Integer getIdAgrupacion() {
        return this.idAgrupacion;
    }

    public void setIdAgrupacion(java.lang.Integer idAgrupacion) {
        this.idAgrupacion = idAgrupacion;
    }
    
    public java.lang.String getNombreAgrupacion() {
        return this.nombreAgrupacion;
    }

    public void setNombreAgrupacion(java.lang.String nombreAgrupacion) {
        this.nombreAgrupacion = nombreAgrupacion;
    }
}
