package org.redhat.bajaservicios;
/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(02448a56d2efe28fe933b5f5ab40ba2d)
 */
@org.kie.api.definition.type.Label(value = "Configuracion")
public class Configuracion extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "ES_RPV1")
    @org.kie.api.definition.type.Position(value = 15)
    private java.lang.Integer ES_RPV1;
    
    @org.kie.api.definition.type.Label(value = "POTSBRA")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Integer POTSBRA;
    
    @org.kie.api.definition.type.Label(value = "Centralita")
    @org.kie.api.definition.type.Position(value = 10)
    private java.lang.Integer centralita;
    
    @org.kie.api.definition.type.Label(value = "ConnectLan")
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.Integer connectLan;
    
    @org.kie.api.definition.type.Label(value = "Despega")
    @org.kie.api.definition.type.Position(value = 12)
    private java.lang.Integer depega;
    
    @org.kie.api.definition.type.Label(value = "DevOtroOperador")
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.Integer devOtroOperador;
    
    @org.kie.api.definition.type.Label(value = "DirIpFijas")
    @org.kie.api.definition.type.Position(value = 16)
    private java.lang.Integer dirIpFijas;
    
    @org.kie.api.definition.type.Label(value = "FechaInst")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String fechaInst;
    
    @org.kie.api.definition.type.Label(value = "ForAut")
    @org.kie.api.definition.type.Position(value = 17)
    private java.lang.Integer forAut;
    
    @org.kie.api.definition.type.Label(value = "MensajeSP")
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.Integer mensajeSP;
    
    @org.kie.api.definition.type.Label(value = "ObservacionOT")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String observacionOT;
    
    @org.kie.api.definition.type.Label(value = "Primario")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Integer primario;
    
    @org.kie.api.definition.type.Label(value = "ProdIndep")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer prodIndep;
    
    @org.kie.api.definition.type.Label(value = "RecogerEquipo")
    @org.kie.api.definition.type.Position(value = 14)
    private java.lang.Integer recogerEquipo;
    
    @org.kie.api.definition.type.Label(value = "ServAdic")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer servAdic;
    
    @org.kie.api.definition.type.Label(value = "Tecnico")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer tecnico;
    
    @org.kie.api.definition.type.Label(value = "Television")
    @org.kie.api.definition.type.Position(value = 13)
    private java.lang.Integer television;
    
    @org.kie.api.definition.type.Label(value = "TipoServicio")
    @org.kie.api.definition.type.Position(value = 0)
    private org.redhat.bajaservicios.TipoServicio tipoServicio;

    public Configuracion() {
    }

    public Configuracion(org.redhat.bajaservicios.TipoServicio tipoServicio, java.lang.Integer tecnico, java.lang.String observacionOT, java.lang.String fechaInst, java.lang.Integer prodIndep, java.lang.Integer primario, java.lang.Integer servAdic, java.lang.Integer POTSBRA, java.lang.Integer devOtroOperador, java.lang.Integer mensajeSP, java.lang.Integer centralita, java.lang.Integer connectLan, java.lang.Integer depega, java.lang.Integer television, java.lang.Integer recogerEquipo, java.lang.Integer ES_RPV1, java.lang.Integer dirIpFijas, java.lang.Integer forAut) {
        this.tipoServicio = tipoServicio;
        this.tecnico = tecnico;
        this.observacionOT = observacionOT;
        this.fechaInst = fechaInst;
        this.prodIndep = prodIndep;
        this.primario = primario;
        this.servAdic = servAdic;
        this.POTSBRA = POTSBRA;
        this.devOtroOperador = devOtroOperador;
        this.mensajeSP = mensajeSP;
        this.centralita = centralita;
        this.connectLan = connectLan;
        this.depega = depega;
        this.television = television;
        this.recogerEquipo = recogerEquipo;
        this.ES_RPV1 = ES_RPV1;
        this.dirIpFijas = dirIpFijas;
        this.forAut = forAut;
    }


    
    public java.lang.Integer getES_RPV1() {
        return this.ES_RPV1;
    }

    public void setES_RPV1(java.lang.Integer ES_RPV1) {
        this.ES_RPV1 = ES_RPV1;
    }
    
    public java.lang.Integer getPOTSBRA() {
        return this.POTSBRA;
    }

    public void setPOTSBRA(java.lang.Integer POTSBRA) {
        this.POTSBRA = POTSBRA;
    }
    
    public java.lang.Integer getCentralita() {
        return this.centralita;
    }

    public void setCentralita(java.lang.Integer centralita) {
        this.centralita = centralita;
    }
    
    public java.lang.Integer getConnectLan() {
        return this.connectLan;
    }

    public void setConnectLan(java.lang.Integer connectLan) {
        this.connectLan = connectLan;
    }
    
    public java.lang.Integer getDepega() {
        return this.depega;
    }

    public void setDepega(java.lang.Integer depega) {
        this.depega = depega;
    }
    
    public java.lang.Integer getDevOtroOperador() {
        return this.devOtroOperador;
    }

    public void setDevOtroOperador(java.lang.Integer devOtroOperador) {
        this.devOtroOperador = devOtroOperador;
    }
    
    public java.lang.Integer getDirIpFijas() {
        return this.dirIpFijas;
    }

    public void setDirIpFijas(java.lang.Integer dirIpFijas) {
        this.dirIpFijas = dirIpFijas;
    }
    
    public java.lang.String getFechaInst() {
        return this.fechaInst;
    }

    public void setFechaInst(java.lang.String fechaInst) {
        this.fechaInst = fechaInst;
    }
    
    public java.lang.Integer getForAut() {
        return this.forAut;
    }

    public void setForAut(java.lang.Integer forAut) {
        this.forAut = forAut;
    }
    
    public java.lang.Integer getMensajeSP() {
        return this.mensajeSP;
    }

    public void setMensajeSP(java.lang.Integer mensajeSP) {
        this.mensajeSP = mensajeSP;
    }
    
    public java.lang.String getObservacionOT() {
        return this.observacionOT;
    }

    public void setObservacionOT(java.lang.String observacionOT) {
        this.observacionOT = observacionOT;
    }
    
    public java.lang.Integer getPrimario() {
        return this.primario;
    }

    public void setPrimario(java.lang.Integer primario) {
        this.primario = primario;
    }
    
    public java.lang.Integer getProdIndep() {
        return this.prodIndep;
    }

    public void setProdIndep(java.lang.Integer prodIndep) {
        this.prodIndep = prodIndep;
    }
    
    public java.lang.Integer getRecogerEquipo() {
        return this.recogerEquipo;
    }

    public void setRecogerEquipo(java.lang.Integer recogerEquipo) {
        this.recogerEquipo = recogerEquipo;
    }
    
    public java.lang.Integer getServAdic() {
        return this.servAdic;
    }

    public void setServAdic(java.lang.Integer servAdic) {
        this.servAdic = servAdic;
    }
    
    public java.lang.Integer getTecnico() {
        return this.tecnico;
    }

    public void setTecnico(java.lang.Integer tecnico) {
        this.tecnico = tecnico;
    }
    
    public java.lang.Integer getTelevision() {
        return this.television;
    }

    public void setTelevision(java.lang.Integer television) {
        this.television = television;
    }
    
    public org.redhat.bajaservicios.TipoServicio getTipoServicio() {
        return this.tipoServicio;
    }

    public void setTipoServicio(org.redhat.bajaservicios.TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }
}
