package org.redhat.bajaservicios;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(bab583fd1ccec3ff680e058840aa2cef)
 */
@org.kie.api.definition.type.Label(value = "Flujos")
public class Flujos extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Codigo Cliente")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer codigo_cliente;
    
    @org.kie.api.definition.type.Label(value = "Estado")
    @org.kie.api.definition.type.Position(value = 10)
    private java.lang.String estado;
    
    @org.kie.api.definition.type.Label(value = "Fecha creacion")
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.Date fecha_creacion;
    
    @org.kie.api.definition.type.Label(value = "Fecha fin estimada")
    @org.kie.api.definition.type.Position(value = 7)
    private java.util.Date fecha_estimada_fin;
    
    @org.kie.api.definition.type.Label(value = "Fecha Fin")
    @org.kie.api.definition.type.Position(value = 6)
    private java.util.Date fecha_fin;
    
    @org.kie.api.definition.type.Label(value = "Fecha fin real")
    @org.kie.api.definition.type.Position(value = 8)
    private java.util.Date fecha_fin_real;
    
    @org.kie.api.definition.type.Label(value = "Fecha inicio")
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.Date fecha_inicio;
    
    @org.kie.api.definition.type.Label(value = "Hito actual")
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.String hitoActual;
    
    @org.kie.api.definition.type.Label(value = "Historico de hitos")
    @org.kie.api.definition.type.Position(value = 12)
    private java.util.List<org.redhat.bajaservicios.Hitos> hitos;
    
    @org.kie.api.definition.type.Label(value = "Id catalogo flujo")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String id_catalogo_flujo;
    
    @org.kie.api.definition.type.Label(value = "id_flujo")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer id_flujo;
    
    @org.kie.api.definition.type.Label(value = "Id_job")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer id_job;
    
    @org.kie.api.definition.type.Label(value = "Producto")
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.String producto;

    public Flujos() {
    }

    public Flujos(java.lang.Integer id_flujo, java.lang.Integer id_job, java.lang.String id_catalogo_flujo, java.lang.Integer codigo_cliente, java.util.Date fecha_creacion, java.util.Date fecha_inicio, java.util.Date fecha_fin, java.util.Date fecha_estimada_fin, java.util.Date fecha_fin_real, java.lang.String producto, java.lang.String estado, java.lang.String hitoActual, java.util.List<org.redhat.bajaservicios.Hitos> hitos) {
        this.id_flujo = id_flujo;
        this.id_job = id_job;
        this.id_catalogo_flujo = id_catalogo_flujo;
        this.codigo_cliente = codigo_cliente;
        this.fecha_creacion = fecha_creacion;
        this.fecha_inicio = fecha_inicio;
        this.fecha_fin = fecha_fin;
        this.fecha_estimada_fin = fecha_estimada_fin;
        this.fecha_fin_real = fecha_fin_real;
        this.producto = producto;
        this.estado = estado;
        this.hitoActual = hitoActual;
        this.hitos = hitos;
    }


    
    public java.lang.Integer getCodigo_cliente() {
        return this.codigo_cliente;
    }

    public void setCodigo_cliente(java.lang.Integer codigo_cliente) {
        this.codigo_cliente = codigo_cliente;
    }
    
    public java.lang.String getEstado() {
        return this.estado;
    }

    public void setEstado(java.lang.String estado) {
        this.estado = estado;
    }
    
    public java.util.Date getFecha_creacion() {
        return this.fecha_creacion;
    }

    public void setFecha_creacion(java.util.Date fecha_creacion) {
        this.fecha_creacion = fecha_creacion;
    }
    
    public java.util.Date getFecha_estimada_fin() {
        return this.fecha_estimada_fin;
    }

    public void setFecha_estimada_fin(java.util.Date fecha_estimada_fin) {
        this.fecha_estimada_fin = fecha_estimada_fin;
    }
    
    public java.util.Date getFecha_fin() {
        return this.fecha_fin;
    }

    public void setFecha_fin(java.util.Date fecha_fin) {
        this.fecha_fin = fecha_fin;
    }
    
    public java.util.Date getFecha_fin_real() {
        return this.fecha_fin_real;
    }

    public void setFecha_fin_real(java.util.Date fecha_fin_real) {
        this.fecha_fin_real = fecha_fin_real;
    }
    
    public java.util.Date getFecha_inicio() {
        return this.fecha_inicio;
    }

    public void setFecha_inicio(java.util.Date fecha_inicio) {
        this.fecha_inicio = fecha_inicio;
    }
    
    public java.lang.String getHitoActual() {
        return this.hitoActual;
    }

    public void setHitoActual(java.lang.String hitoActual) {
        this.hitoActual = hitoActual;
    }
    
    public java.util.List<org.redhat.bajaservicios.Hitos> getHitos() {
        return this.hitos;
    }

    public void setHitos(java.util.List<org.redhat.bajaservicios.Hitos> hitos) {
        this.hitos = hitos;
    }
    
    public java.lang.String getId_catalogo_flujo() {
        return this.id_catalogo_flujo;
    }

    public void setId_catalogo_flujo(java.lang.String id_catalogo_flujo) {
        this.id_catalogo_flujo = id_catalogo_flujo;
    }
    
    public java.lang.Integer getId_flujo() {
        return this.id_flujo;
    }

    public void setId_flujo(java.lang.Integer id_flujo) {
        this.id_flujo = id_flujo;
    }
    
    public java.lang.Integer getId_job() {
        return this.id_job;
    }

    public void setId_job(java.lang.Integer id_job) {
        this.id_job = id_job;
    }
    
    public java.lang.String getProducto() {
        return this.producto;
    }

    public void setProducto(java.lang.String producto) {
        this.producto = producto;
    }
}