package org.redhat.bajaservicios;
/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(3d444bafd1d78e1d58212f3f821b5869)
 */
@org.kie.api.definition.type.Label(value = "FlujoProvision")
public class FlujoProvision  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "IdentCat")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer identCat;
    
    @org.kie.api.definition.type.Label(value = "Identificativo")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer identificativo;
    
    @org.kie.api.definition.type.Label(value = "Prioridad")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer prioridad;

    public FlujoProvision() {
    }

    public FlujoProvision(java.lang.Integer identificativo, java.lang.Integer identCat, java.lang.Integer prioridad) {
        this.identificativo = identificativo;
        this.identCat = identCat;
        this.prioridad = prioridad;
    }


    
    public java.lang.Integer getIdentCat() {
        return this.identCat;
    }

    public void setIdentCat(java.lang.Integer identCat) {
        this.identCat = identCat;
    }
    
    public java.lang.Integer getIdentificativo() {
        return this.identificativo;
    }

    public void setIdentificativo(java.lang.Integer identificativo) {
        this.identificativo = identificativo;
    }
    
    public java.lang.Integer getPrioridad() {
        return this.prioridad;
    }

    public void setPrioridad(java.lang.Integer prioridad) {
        this.prioridad = prioridad;
    }
}
