package org.redhat.bajaservicios;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(ed3c6122309ec98aa13331adb480eaf9)
 */
@org.kie.api.definition.type.Label(value = "Hitos")
public class Hitos  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "descripcion")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String descripcion;
    
    @org.kie.api.definition.type.Label(value = "fecha")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date fecha;
    
    @org.kie.api.definition.type.Label(value = "id")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer id;

    public Hitos() {
    }

    public Hitos(java.lang.Integer id, java.lang.String descripcion, java.util.Date fecha) {
        this.id = id;
        this.descripcion = descripcion;
        this.fecha = fecha;
    }


    
    public java.lang.String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(java.lang.String descripcion) {
        this.descripcion = descripcion;
    }
    
    public java.util.Date getFecha() {
        return this.fecha;
    }

    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }
    
    public java.lang.Integer getId() {
        return this.id;
    }

    public void setId(java.lang.Integer id) {
        this.id = id;
    }
}