package org.redhat.bajaservicios;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(2b1d1b670c9f47e5b65f418bb455bf58)
 */
@org.kie.api.definition.type.Label(value = "OrdenServicio")
public class OrdenServicio extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Cliente")
    @org.kie.api.definition.type.Position(value = 0)
    private org.redhat.bajaservicios.Cliente cliente;
    
    @org.kie.api.definition.type.Label(value = "Fujo")
    @org.kie.api.definition.type.Position(value = 3)
    private org.redhat.bajaservicios.Flujos flujo;
    
    @org.kie.api.definition.type.Label(value = "FlujoProvision")
    @org.kie.api.definition.type.Position(value = 1)
    private org.redhat.bajaservicios.FlujoProvision flujoProvision;
    
    @org.kie.api.definition.type.Label(value = "Observaciones")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String observaciones;
    
    @org.kie.api.definition.type.Label(value = "ProductoComercial")
    @org.kie.api.definition.type.Position(value = 2)
    private org.redhat.bajaservicios.ProductoComercial productoComercial;
    
    @org.kie.api.definition.type.Label(value = "pruebaFinal")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer pruebaFinal;

    public OrdenServicio() {
    }

    public OrdenServicio(org.redhat.bajaservicios.Cliente cliente, org.redhat.bajaservicios.FlujoProvision flujoProvision, org.redhat.bajaservicios.ProductoComercial productoComercial, org.redhat.bajaservicios.Flujos flujo, java.lang.Integer pruebaFinal, java.lang.String observaciones) {
        this.cliente = cliente;
        this.flujoProvision = flujoProvision;
        this.productoComercial = productoComercial;
        this.flujo = flujo;
        this.pruebaFinal = pruebaFinal;
        this.observaciones = observaciones;
    }


    
    public org.redhat.bajaservicios.Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(org.redhat.bajaservicios.Cliente cliente) {
        this.cliente = cliente;
    }
    
    public org.redhat.bajaservicios.Flujos getFlujo() {
        return this.flujo;
    }

    public void setFlujo(org.redhat.bajaservicios.Flujos flujo) {
        this.flujo = flujo;
    }
    
    public org.redhat.bajaservicios.FlujoProvision getFlujoProvision() {
        return this.flujoProvision;
    }

    public void setFlujoProvision(org.redhat.bajaservicios.FlujoProvision flujoProvision) {
        this.flujoProvision = flujoProvision;
    }
    
    public java.lang.String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(java.lang.String observaciones) {
        this.observaciones = observaciones;
    }
    
    public org.redhat.bajaservicios.ProductoComercial getProductoComercial() {
        return this.productoComercial;
    }

    public void setProductoComercial(org.redhat.bajaservicios.ProductoComercial productoComercial) {
        this.productoComercial = productoComercial;
    }
    
    public java.lang.Integer getPruebaFinal() {
        return this.pruebaFinal;
    }

    public void setPruebaFinal(java.lang.Integer pruebaFinal) {
        this.pruebaFinal = pruebaFinal;
    }
}