package org.redhat.bajaservicios;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(2d5e39604705786276fe3eabc9d7061e)
 */
@org.kie.api.definition.type.Label(value = "ProductoComercial")
public class ProductoComercial extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Configuracion")
    @org.kie.api.definition.type.Position(value = 1)
    private org.redhat.bajaservicios.Configuracion configuracion;
    
    @org.kie.api.definition.type.Label(value = "Nombre")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String nombre;

    public ProductoComercial() {
    }

    public ProductoComercial(java.lang.String nombre, org.redhat.bajaservicios.Configuracion configuracion) {
        this.nombre = nombre;
        this.configuracion = configuracion;
    }


    
    public org.redhat.bajaservicios.Configuracion getConfiguracion() {
        return this.configuracion;
    }

    public void setConfiguracion(org.redhat.bajaservicios.Configuracion configuracion) {
        this.configuracion = configuracion;
    }
    
    public java.lang.String getNombre() {
        return this.nombre;
    }

    public void setNombre(java.lang.String nombre) {
        this.nombre = nombre;
    }
}
