package org.redhat.bajaservicios;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(4b458b0e18166c316ea32e3a468c42fe)
 */
@org.kie.api.definition.type.Label(value = "TipoServicio")
public class TipoServicio  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Instalacion")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer instalacion;
    
    @org.kie.api.definition.type.Label(value = "Red")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer red;
    
    @org.kie.api.definition.type.Label(value = "Tecnico")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer tecnico;

    public TipoServicio() {
    }

    public TipoServicio(java.lang.Integer instalacion, java.lang.Integer red, java.lang.Integer tecnico) {
        this.instalacion = instalacion;
        this.red = red;
        this.tecnico = tecnico;
    }


    
    public java.lang.Integer getInstalacion() {
        return this.instalacion;
    }

    public void setInstalacion(java.lang.Integer instalacion) {
        this.instalacion = instalacion;
    }
    
    public java.lang.Integer getRed() {
        return this.red;
    }

    public void setRed(java.lang.Integer red) {
        this.red = red;
    }
    
    public java.lang.Integer getTecnico() {
        return this.tecnico;
    }

    public void setTecnico(java.lang.Integer tecnico) {
        this.tecnico = tecnico;
    }
}
